### ISSUE TITLE
Stream objects all have their pivot at world origin

### ISSUE THREAD

**Issue by pablothedolphin** [speckleworks/SpeckleUnity#60]
This throws off things like transparency culling and also limits the usecases of objects once received.

**Comment by tsvilans** [comment]
Another good reason to implement the `transform` property on Speckle objects! @didimitrie

**Comment by pablothedolphin** [comment]
@tsvilans has this been debated for a while? I was just going to create a new transform at the centre of the vertices of each mesh, subtract that offset from each vertex to realign them and call it a job done. 

Though I would want to hold off on my changes if this is going to be supported naively by speckle...

**Comment by tsvilans** [comment]
@pablothedolphin Sometimes a `transform` property appears in a Speckle object schema, but the other clients haven't really integrated it, since Rhino et al. don't have a separation between model and model data. The Blender client does check for this, and uses a 4x4 transform matrix if it is found, so it considers the object data as being in local / object space...

Maybe with enough pushing we can get this better supported ;) 

I'd say, for now, you can re-centre the object data upon import? I guess it needs to be decided whether or not the incoming Speckle data is in local or global space...

**Comment by cwmorse** [comment]
As someone who works mostly with Rhino, I think the re-centre plan makes sense since Rhino geometry won't have a transform. 

But also I could see situations where I don't want it to add transforms and would rather keep the data as close to parity with Rhino as possible. So if this could be an optional toggle, that would be ideal for me.

**Comment by pablothedolphin** [comment]
Thanks for the feedback @cwmorse ! Toggling the feature should be no problem I'll add that in today!
